-d C:\Users\furka\Desktop\sifrelemeSistemi\impl\gwsynthesis\sifrelemeSistemi.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\furka\Desktop\sifrelemeSistemi\src\sifrelemeSistemi.cst
-cfg C:\Users\furka\Desktop\sifrelemeSistemi\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 10
